# Generated by Django 5.0.2 on 2025-04-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faqstranslation",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="faqstranslation",
            name="question",
        ),
        migrations.AddField(
            model_name="faqs",
            name="questions",
            field=models.JSONField(
                default=list,
                help_text="Format: [{'question': '...', 'answer': '...'}, ...]",
            ),
        ),
    ]
