# Generated by Django 5.0.2 on 2025-04-20 04:04

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_remove_faqstranslation_answer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqs",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQs"},
        ),
        migrations.AlterModelOptions(
            name="faqstranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "FAQ Translation",
            },
        ),
        migrations.RemoveField(
            model_name="faqs",
            name="questions",
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_answers",
                        to="about.faqs",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="QuestionAnswerTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", ckeditor.fields.RichTextField()),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="about.questionanswer",
                    ),
                ),
            ],
            options={
                "verbose_name": "question answer Translation",
                "db_table": "about_questionanswer_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
