# Generated by Django 5.0.2 on 2025-04-20 17:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0004_brand_opimage_aboutcompany_aboutcompanytranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutcompanytranslation",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="questionanswertranslation",
            name="answer",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
