# Generated by Django 5.0.2 on 2025-04-23 15:06

import apps.utils
import ckeditor.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0005_alter_aboutcompanytranslation_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutcompany",
            options={},
        ),
        migrations.AlterModelOptions(
            name="aboutcompanytranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "about company Translation",
            },
        ),
        migrations.AlterField(
            model_name="aboutcompany",
            name="image",
            field=models.ImageField(
                default=1, upload_to=apps.utils.generate_unique_filename
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aboutcompanytranslation",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionanswertranslation",
            name="answer",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
