# Generated by Django 5.0.2 on 2025-04-23 15:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0006_alter_aboutcompany_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswertranslation",
            name="answer",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
