# Generated by Django 5.0.2 on 2025-04-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0008_telegramuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram Bot",
                "verbose_name_plural": "Telegram Bots",
            },
        ),
    ]
