# Generated by Django 5.0.2 on 2025-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0009_telegrambot"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambot",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="telegrambot",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
