# Generated by Django 5.0.2 on 2025-04-20 01:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannertranslation",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categorytranslation",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
