# Generated by Django 5.0.2 on 2025-04-20 04:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_shortdescriptiontranslation_value_barcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortdescriptiontranslation",
            name="value",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
